### PR TITLE
Split into three sections

### PR DESCRIPTION
**Pull request by nouyang-curoverse**

### CODE REVIEW

**Comment by celiafw** [comment]
Thanks Nancy, 
I’ve got to get the kids at school but I will take a look when I get back and let you know. 

Talk tomorrow? My guess is its close to done. 

Celia

**Comment by nouyang-curoverse** [comment]
Let's talk tomorrow -- I'm in the middle of a lot of changes, but since we
thought the splitting into three sections was fine, I went ahead and merged
it to the "official" version.
Thanks,
--Nancy

**Comment by celiafw** [comment]
It looks good! I will be working on more content editing tonight unless you
think I shouldn't given the ideas you have. I don't want to do double work
or create more work for you

Celia

**Comment by nouyang-curoverse** [comment]
We manually merged already.

**Comment by celiafw** [comment]
Nancy,
I think we did everything, right? Just waiting to find out if content is ok
per staff, Madeleine, and Jason. So far, no response other than "looks
pretty good"

Celia

**Pull request closed without merging**
